library(qqman)
library(lattice)
setwd("/home/pang/Desktop/CAD_IS_PAD_20200121/data/SNP")
cad<-read.table("cadmeta",as.is=TRUE,header=TRUE)
is<-read.table("ismeta",as.is=TRUE,header=TRUE)
pad<-read.table("padmeta",as.is=TRUE,header=TRUE)
png("cadmeta.png")
manhattan(cad, chr="Chr", bp="BP", snp="Marker", p="pValue" )
dev.off()
png("ismeta.png")
manhattan(is, chr="Chr", bp="BP", snp="Marker", p="pValue" )
dev.off()
png("padmeta.png")
manhattan(pad, chr="Chr", bp="BP", snp="Marker", p="pValue" )
dev.off()

